services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: Armando_neto
      POSTGRES_PASSWORD: 133601
      POSTGRES_DB: Armando_neto_db
    ports: 
      - "5433:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://Armando_neto:133601@db:5433/Armando_neto_db
volumes:
  db_data: